### ISSUE TITLE
new data

### ISSUE THREAD

**Issue by xudekuan** [JerrikEph/Capsule4TextClassification#1]
Is it possible to use the users' data for the model? and what are the requirements for the data format?
Thank you very much for your kindly answer.

**Comment by jingjing-gong** [comment]
Hi, @xudekuan 

Data Downloading process is specified in data/downloadDataset.md. You can check downloaded files, transfom your new dataset to similar format, note that data format for flatten version is different from that of hierarchical version.

**Comment by xudekuan** [comment]
Ok, I will try it. Thank you very much.

**Comment by xudekuan** [comment]
I found there numbers like the followings in the /data/smallset/imdb/devset.pkl, is it right?
[(6, [[17, 27, 1436, 13, 7503, 6, 50, 17, 420, 10, 2791, 66, 20, 55468, 39954, 26563, 678, 7], [18, 822, 29, 78, 341, 41, 8637, 43, 115, 31, 1, 30, 349, 65, 6, 111, 45, 6, 27, 39954, 205, 604, 7], [14, 12, 9, 58, 64, 21, 17, 135, 45, 5, 443, 8, 1627, 3413, 14, 9, 190, 7], [14, 12, 769, 1296, 38, 31, 3513, 4919, 30, 6, 8, 14, 12, 131, 170, 31, 5, 1802, 30, 7], [718, 6, 5483, 3594, 12, 61, 58,

**Comment by jingjing-gong** [comment]
Leading Integer is the class id, the integers in nested list are word ids, Class name or word can be further indexed from corresponding vocabulary.

**Comment by xudekuan** [comment]
Thank you very much for your prompt rely.
If I had the data with format in words, just like this:
[news[this is an example for news]]
"news" is the id and [this is an example for news] are contents.
Is it possilble to use your code to do the experiment?
Thanks again for your reply.
